.Dd January  1, 2015
.Dt libclocale 3
.Os libclocale
.Sh NAME
.Nm libclocale.h
.Nd Library to support cross-platform C locale functions
.Sh LIBRARY
.Lb libclocale
.Sh SYNOPSIS
.In libclocale.h
.Pp
Support functions
.Ft const char *
.Fn libclocale_get_version "void"
.Ft int
.Fn libclocale_initialize "const char *domain_name, libclocale_error_t **error"
.Pp
Codepage functions
.Ft int
.Fn libclocale_codepage_get "int *codepage, libclocale_error_t **error"
.Ft int
.Fn libclocale_codepage_set "int codepage, libclocale_error_t **error"
.Ft int
.Fn libclocale_codepage_copy_from_string "int *codepage, const char *string, size_t string_length, uint32_t feature_flags, libclocale_error_t **error"
.Ft int
.Fn libclocale_codepage_copy_from_string_wide "int *codepage, const wchar_t *string, size_t string_length, uint32_t feature_flags, libclocale_error_t **error"
.Pp
Locale functions
.Ft int
.Fn libclocale_locale_get_codepage "int *codepage, libclocale_error_t **error"
.Ft int
.Fn libclocale_locale_get_decimal_point "int *decimal_point, libclocale_error_t **error"
.Sh DESCRIPTION
The
.Fn libclocale_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or -1 on error, dependent on the return type.
For the actual return values see "libclocale.h".
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh BUGS
Please report bugs of any kind on the project issue tracker: https://github.com/libyal/libclocale/issues
.Sh AUTHOR
These man pages are generated from "libclocale.h".
.Sh COPYRIGHT
Copyright (C) 2010-2015, Joachim Metz <joachim.metz@gmail.com>.

This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
the libclocale.h include file
